# By default, Cirrus mounts an empty volume to `/tmp`
# which triggers all sorts of warnings like "system temporary path is world-writable: /tmp".
# Lets workaround it by specifying a custom volume mount point.
env:
  CIRRUS_VOLUME: /cirrus-ci-volume

task:
  # The entire testing design is inspired from .github/workflows/compilers.yml .
  name: Arm64 Graviton2 / $CC
  arm_container:
    # We use the arm64 images at http://ghcr.io/ruby/ruby-ci-image .
    image: ghcr.io/ruby/ruby-ci-image:$CC
    # Define the used cpu core in each matrix task. We can use total 16 cpu
    # cores in entire matrix. [cpu] = [total cpu: 16] / [number of tasks]
    cpu: 8
    # We can request maximum 4 GB per cpu.
    # [memory per task] = [memory per cpu: 4 GB] * [cpu]
    memory: 32G
  env:
    CIRRUS_CLONE_DEPTH: 50
    optflags: '-O1'
    debugflags: '-ggdb3'
    RUBY_PREFIX: /tmp/ruby-prefix
    RUBY_DEBUG: ci rgengc
    RUBY_TESTOPTS: >-
      -q
      --color=always
      --tty=no
    matrix:
      CC: clang-12
      CC: gcc-11
  id_script: id
  set_env_script:
    # Use `make_cmd` instead of `make` environment variable,
    # because the `make` environment variable is used in rubygems,
    # and some rubygems tests fail in this case.
    # https://github.com/rubygems/rubygems/issues/4921
    - echo "make_cmd=make -s -j$((1 + $CIRRUS_CPU))" >> $CIRRUS_ENV
  print_env_script:
    - echo "make_cmd=$make_cmd"
  # Set any timezone to pass the tests.
  set_timezone_script: sudo ln -snf /usr/share/zoneinfo/Japan /etc/localtime
  dpkg-reconfigure_script: sudo dpkg-reconfigure --frontend noninteractive tzdata
  # Arm containers are executed in AWS's EKS, and it's not yet supporting IPv6
  # See https://github.com/aws/containers-roadmap/issues/835
  disable_ipv6_script: sudo ./tool/disable_ipv6.sh
  autogen_script: ./autogen.sh
  configure_script: >-
    ./configure -C
    --enable-debug-env
    --disable-install-doc
    --with-ext=-test-/cxxanyargs,+
    --prefix="$RUBY_PREFIX"
  make_extract-extlibs_script: $make_cmd extract-extlibs
  make_incs_script: $make_cmd incs
  make_script: $make_cmd
  make_leaked-globals_script: $make_cmd leaked-globals
  make_test_script: $make_cmd test
  make_install_script: $make_cmd install
  install_gems_for_test_script: $RUBY_PREFIX/bin/gem install --no-doc timezone tzinfo
  make_test-tool_script: $make_cmd test-tool
  make_test-all_script: $make_cmd test-all
  make_test-spec_script: $make_cmd test-spec
