# Copyright (C) 2011 Urabe, Shyouhei.  All rights reserved.
#
# This file is  a part of the programming language  Ruby.  Permission is hereby
# granted,  to either  redistribute  or  modify this  file,  provided that  the
# conditions  mentioned in  the file  COPYING are  met.  Consult  the  file for
# details.

# This is  a Travis-CI  build configuration file.   The list  of configurations
# available is located in
#
#     http://about.travis-ci.org/docs/user/build-configuration/
#
# and as Ruby itself is a project written in C language,
#
#     http://about.travis-ci.org/docs/user/languages/c/
#
# is also a good place to look at.

language: c
dist: trusty

sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "BBNCt+4KMRDAGb0jPM3JJFwJ6kDJfQa31f8mLALZX4MHBOsQnGkbrdx2GfcZ2WSq9Jo7S4pT+YrW7mc3M5LowHS7yFVNEoYhn52MbZ2CTKUdtxoy0FuMfnPkk3UploXuruVHDp4Ny7FlMRc5dxFwOkekWegBKEvopIU9tT7Dsi85vABygUUKMSLCd9L0nj8+tKNMKZaD+sgeNQ3Ujr5r/N1Z/GarCC6pFkL1ShhojqDsNBOcPX34JddS/zQXrEwNEEcaxv3QBVDZdPSs2ZdsCr2iiWWVcqOnBAQYEfAhqC206Gxs4VE4rG1/0S9uRswI2uyLJKDbzSY9vtikJGTHwOyVhNEPuwkCZvKjWcgddY1NyNa2rly5TKKTs92h6k1zBHL42LyFqC2EwvCZ+cM4F2+lOUwEgRNd3tqoNxFsbTGsfdH9scm13lsjI0/hVBw9UALEIO22Lzo4wBN4GFtZ9Xm/kO86ppyEqTwFLQ2Urj/SdUHyZBLoM4eqSOWsBx+aTlPkex6PELRR1VZ9Q8ZcErUwhaRAlLh5JNycqWctJFKIyPJU63GQmg9Ax1bMT2UrjuvTzvdRoDu2eWMESw4pe5JTgWDEqrQcFNPXtr3oRcMCzPJLcyguhJFI6tkgM4u+i+zERfMik3IsRagiqF9Sf5IcYaL9XQNHcyUl7iyQNV8="

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
        coverity_scan:
          project:
            name: "junaruga/ruby"
            description: "Build submitted via Travis CI"
          notification_email: happy@oh4u.net
          build_command_prepend: autoconf && ./configure
          build_command: make -j2
          branch_pattern: travis-coverity-scan
      install:
        - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - os: linux
      language: ruby
      rvm: 2.3
      name: Running ruby/spec on 2.3 to ensure version guards are correctly added
      before_install:
      install:
      before_script: chmod -R u+w spec/ruby
      script: ruby -C spec/ruby ../mspec/bin/mspec -j .

before_install:
  - "CONFIG_FLAG="
  - "JOBS=-j`nproc`"

before_script:
  - "echo JOBS=$JOBS"
  - "uname -a"
  - "uname -r"
  - "rm -fr .ext autom4te.cache"
  - "echo $TERM"
  - "> config.status"
  - "sed -f tool/prereq.status Makefile.in common.mk > Makefile"
  - "make update-config_files"
  - "make touch-unicode-files"
  - "make -s $JOBS srcs UNICODE_FILES=."
  - "requests=; for req in ${RUBYSPEC_PULL_REQUEST//,/ }; do
      requests=\"$requests +refs/pull/$req/merge:\";
    done"
  - "${requests:+git -C spec/ruby -c user.email=none -c user.name=none pull --no-edit origin $requests}"
  - "${requests:+git -C spec/ruby log --oneline origin/master..@}"
  - "rm config.status Makefile rbconfig.rb .rbconfig.time"
  - "mkdir build config_1st config_2nd"
  - "chmod -R a-w ."
  - "chmod u+w build config_1st config_2nd"
  - "cd build"
  - "../configure -C --disable-install-doc --prefix=/tmp/ruby-prefix --with-gcc=$CC $CONFIG_FLAG"
  - "cp -pr config.cache config.status .ext/include ../config_1st"
  - "make reconfig"
  - "cp -pr config.cache config.status .ext/include ../config_2nd"
  - "(cd .. && exec diff -ru config_1st config_2nd)"
  - "make -s $JOBS && make install"

script:
  - "make -s test TESTOPTS=--color=never"
  - "make -s $JOBS test-all -o exts TESTOPTS='-q --color=never --job-status=normal' RUBY_FORCE_TEST_JIT=1"
  - "make -s $JOBS test-spec MSPECOPT=-j"

# Branch matrix.  Not all branches are Travis-ready so we limit branches here.
branches:
  only:
    - trunk
    - ruby_2_3
    - ruby_2_4
    - ruby_2_5
    - /^feature\//
    - /^bug\//
    - /^travis-/

# We want to be notified when something happens.
notifications:
  irc:
    channels:
      - "chat.freenode.net#ruby-core"
      - "chat.freenode.net#ruby-ja"
    on_success: change # [always|never|change] # default: always
    on_failure: always # [always|never|change] # default: always
    template:
      - "%{message} by @%{author}: See %{build_url}"

  slack:
    rooms:
      - secure: i1GLETSKye85ea6dGNA3MxI/5myChmMFiZtBd5C69xK+s1sBFqEgOSbaSf9KHc0CYrHVyNhQMaZRruieV7xS+6Pfs0Zvxf1DO6QQTWC2KhkqwFDLvZncAzjoyASdR90hbr+iRPOngQ+HJuE94zemALAwEqNAinzA74PMiJXktqY= # ruby:<token>#commits
      - secure: ah7UEHBvncXT7bM5mvYIQAO+tIyV/wl7nXLb7wQD16dO2v8Gragy0mWjB79Q09hrrMGmp6H9bCDpdGS80boIA5EHaHoG4QaP0i9bsSt8U2AMWgZtfyIgQKJ4H2kXkGlrjO+AXTgnIkP7LNjdgAVUUTGQPb26T3QmoN2Splt+fIQ= # ruby:<token>#alerts
    on_pull_requests: false
    on_success: change
    on_failure: always

  email:
    - ko1c-failure@atdot.net

# Local Variables:
# mode: YAML
# coding: utf-8-unix
# indent-tabs-mode: nil
# tab-width: 4
# fill-column: 79
# default-justification: full
# End:
